# Autogenerate README.md

printf "
;; [![build status](https://travis-ci.org/NewCircleMovement/lemon.svg?branch=master)](https://travis-ci.org/NewCircleMovement/lemon)
;; [![cljs dependency status](http://jarkeeper.com/NewCircleMovement/lemon/status.png)](http://jarkeeper.com/NewCircleMovement/lemon)
;; [![node.js dependency status](https://david-dm.org/NewCircleMovement/lemon.svg)](https://david-dm.org/NewCircleMovement/lemon)
;;
;; \`autogenerated README.md from literate source code, do not edit directly\`
;;
" | 
cat - src/*/lemon.cljs |
tr "\n" "\r" |
sed -e "s/\(\r;;[^\r]*\r\)\([^;]\)/\1\r\2/g" |
tr "\r" "\n" |
sed -e "s/^/    /" |
sed -e "s/^ *;; \\?//" \
  > README.md
